name: Convention checks
run-name: Convention checks

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!main'
  pull_request:
    types: [opened, reopened, edited]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: valid branch name
        run: |
          if [[ ${GITHUB_REF#refs/heads/} != refs/pull* ]] && [[ ${GITHUB_REF#refs/heads/} != feature* ]]; then
            echo ${GITHUB_REF#refs/heads}
            exit 1;
          fi

      - uses: deepakputhraya/action-pr-title@master
        if: ${{ github.event_name == 'pull_request' }}
        with:
          regex: '\[[a-zA-Z0.9-]*\].*' # Regex the title should match.