name: CI/CD Develop
run-name: CI/CD Develop

on:
  push:
    branches: develop

jobs:
  generate_pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Generate files
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          install -m 600 -D /dev/null ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          git config user.name 'postmanbuilder[bot]'
          git config user.email 'postmanbuilder[bot]@users.noreply.github.com'
          pip install -r ./scripts/git_test/requirements.txt
          python ./scripts/git_test/create_files.py
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_SECRET }}
      - name: Create PR
        run: |
          curl --request POST \
          --header 'authorization: Bearer ${{ steps.generate_token.outputs.token }}' \
          --header 'content-type: application/json' \
          --url 'https://api.github.com/repos/pigmeister/node-weather-website/pulls' \
          --data '{
            "title": "Test curl PR",
            "body": "Test PR using curl",
            "head": "test-head",
            "base": "test-base"
          }'