name: CI/CD Develop
run-name: CI/CD Develop

on:
  push:
    branches: 'develop'

jobs:
  generate_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7'
        cache: 'pip'
    - name: Generate file
      run: |
        mkdir ./output
        pip install -r ./scripts/git_test/requirements.txt
        python ./scripts/git_test/create_files.py
    - name: Pushes to public repository
      uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: './output/'
        destination-github-username: 'pigmeister'
        destination-repository-name: 'node-weather-website'
        user-email: 'github-actions[bot]@users.noreply.github.com'
        commit-message: 'Added new files'
        target-branch: test-head
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.GH_APP_ID }}
        private_key: ${{ secrets.GH_APP_SECRET }}
    - name: Move file and create PR
      env:
        TOKEN: ${{ steps.generate_token.outputs.token }}
      working-directory: dest
      run: |
        python ./scripts/git_test/git_test.py  
