name: CI/CD Develop
run-name: CI/CD Develop

on:
  push:
    branches: develop

jobs:
  generate_pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pip'